### ISSUE TITLE
Download funktioniert bei einigen Veranstaltungen nicht

### ISSUE THREAD

**Issue by IneedThatDownload** [RIVEK-Development/StudIP-Video-Download#1]
Moin erstmal.

Technische hochpräzise ausgedrückt: Download funktioniert bei einigen Veranstaltungen nicht, Download Button(s) sind da, beim draufklicken passiert leider nichts. (also weder im StudIP, noch im Opencast Tab)

In der Konsole zu den Chrome DevTools kommt jedes mal beim Klick auf Download folgende Fehlermelung: 
"Uncaught (in promise) Error: Invalid filename" background.js:1

Bei anderen ,gleich aufgebauten, Veranstaltungen funktioniert es super, auch keine Fehlermedlung.

Ansonsten: Sehr nützliches Plugin 9/10

**Comment by RIVEK-Development** [comment]
Danke für das Feedback.

Es würde mir sehr helfen, wenn ich den Link im Opencast-Player eines dieser Videos hätte. Der sollte wie folgt aussehen:
opencast-present.tu-braunschweig.de/paella/ui/watch.html?id=ccbabdeb-f529-4b36-afd1-5b097d194c43

**Comment by IneedThatDownload** [comment]
Hier: https://opencast-present.tu-braunschweig.de/paella/ui/watch.html?id=e12a8cac-d8d8-4584-b6ac-2ee5076d953e

**Comment by RIVEK-Development** [comment]
Erstmal vielen Dank für die zügige Antwort.

Ich habe scheinbar keinen Berechtigung für das Video, sofern es nicht gelöscht wurde. Daher wäre es hilfreich wenn du mir zeigen könntest was du bekommst, wenn du diesen Link öffnest:
https://opencast-present.tu-braunschweig.de/search/episode.json?id=e12a8cac-d8d8-4584-b6ac-2ee5076d953e
während du im Browser im StudIP eingeloggt bist. Am besten du speicherst das .json wie im angehengten Bild und schickst mir die Datei
![Screenshot (1)](https://user-images.githubusercontent.com/55654812/191095361-b6a99484-b047-4ce3-9b6d-30f140c7ae97.png)

**Comment by RIVEK-Development** [comment]
797f57aa63f521b3fe56f27a1ec999fc9ddd11c9

Falls das Problem nur darin liegt, dass kein Dateiname geliefert wird sollte die V1.5.2 das Problem lösen.
Ich habe die Version auch schon im Chrome Web Store eingereicht die Überprüfung wird jedoch erst morgen abgeschlossen sein.

**Comment by IneedThatDownload** [comment]
Moin nochmal.
Unter Vers. 1.5.2. besteht das Problem leider immer noch.

Ich hab dir die .json Datei per Mail geschickt.

Die Veranstaltung aus der das Opencast-Video ist heißt "Vorlesung: Grundlagen der Produktentwicklung und Konstruktion [WiSe 2021/22]" aktuell ist die Anmeldung nicht beschränkt.

**Comment by RIVEK-Development** [comment]
Vielen Dank

b6a97ad2ea5098194fbf9cab1cbbcccf5d23269b
Mit diesem Update läuft es zumindest in der von dir genannten Veranstaltung. Der Dateiname darf den im Titel stehenden | nicht enthalten und muss. Daher wird nun auch | gelöscht. Ich hoffe, dass es sich in den anderen Veranstaltungen um das gleiche Problem handelt

**Comment by IneedThatDownload** [comment]
Mega nice.
Jetzt funktioniert alles.
10/10

**Comment by RIVEK-Development** [comment]
super
